# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    targetFramework: net10.0
    target-branch: main
    versioning-strategy: increase
    reviewers:
      - "trejjam" # Jan Trejbal
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore"
      include: "scope" # Adds the dependency name to the commit message
    groups:
      microsoft:
        patterns:
          - Microsoft.*
          - System.*
      xunit:
        patterns:
          - xunit
          - xunit.*
    ignore:
      - dependency-name: "Microsoft.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
