name: 'Fetch GraphQL Schema'
description: 'Fetches and processes GraphQL schema from a specified endpoint'

inputs:
  endpoint:
    description: 'GraphQL endpoint URL'
    required: true
  access_token:
    description: 'Access token for authorization'
    required: true

outputs:
  schema_path:
    description: 'Path to the generated schema file'
    value: ${{ steps.fetch_schema.outputs.schema_path }}

runs:
  using: 'composite'
  steps:
    - id: fetch_schema
      shell: bash
      run: |
        cd src/Aviationexam.MoneyErp.GraphQl

        curl -sS -f -X POST "${{ inputs.endpoint }}/graphql" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ inputs.access_token }}" \
             -d '{ "query": "query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name } } } }" }' \
             > schema.json

        jq '{data: .Data}' schema.json > schema-fixed.json

        npm install -g graphql-json-to-sdl
        graphql-json-to-sdl schema-fixed.json schema.graphql

        echo "schema_path=src/Aviationexam.MoneyErp.GraphQl/schema.graphql" >> "$GITHUB_OUTPUT"
