name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types: [checks_requested]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This will fetch the full history
      - name: Get schema.graphql
        run: |
          RUN_ID=$(gh run list --workflow build.yml --status success --limit 1 --json databaseId -q ".[0].databaseId")
          gh run download $RUN_ID -n schema.graphql -D src/Aviationexam.MoneyErp.Graphql
          ls -la src/Aviationexam.MoneyErp.Graphql/schema.graphql
      - name: Tool restore
        run: dotnet tool restore
      - name: Restore
        run: dotnet restore --nologo
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .Net 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag
